#!/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/bin/python
# EASY-INSTALL-SCRIPT: 'avro==1.7.7','avro'
__requires__ = 'avro==1.7.7'
import pkg_resources
pkg_resources.run_script('avro==1.7.7', 'avro')
