#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $DIR
source $DIR/env_python3.cfg
NPROC=$(nproc)

regionsDir=$1
pushd $regionsDir


ABP1="snakemake --rerun-incomplete -p --cores $NPROC -s $DIR/ABP1.py $2 $3 $4"
ABP2="snakemake --rerun-incomplete -p --cores $NPROC -s $DIR/ABP2.py $2 $3 $4"

# run the pipeline
if [ "$1" == "ABP1" ]; then
	$ABP1 
elif [ "$1" == "ABP2" ]; then
	$ABP2
else
	$ABP1 && $ABP2
fi 




popd



