#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/env_python3.cfg
NPROC=$(nproc)

regionsDir=$1
pushd $regionsDir

# sometimes snakemake fails in a really bad way and it leaves to lock on the dir
# this is probably bad practive but oh well
if [ "unlock" == "unlockx" ]; then
    snakemake --unlock -s $DIR/ABP1.py
    snakemake --unlock -s $DIR/ABP2.py
fi


# run the pipeline
if [ "$1" == "ABP1" ]; then
    # creats the partitioned groups from reads.orin.bam ref.fasta, and duplicaitons.fasta
    snakemake -p -s $DIR/ABP1.py
elif [ "$1" == "ABP2" ]; then
    # creats the assemblies from the output of PSV1.py
    snakemake -p -s $DIR/ABP2.py
else
    echo "Running ABP1 and ABP2"
    snakemake --rerun-incomplete -p --cores $NPROC -s $DIR/ABP1.py \
		&& snakemake --rerun-incomplete -p --cores $NPROC -s $DIR/ABP2.py 
fi 

popd


